=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/custom_char_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "custom_char_schema.json",
  "type": "object",
  "properties": {
    "animation": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "object",
          "properties": {
            "name": { "type": "string"},
            "loop": { "type": "boolean"},
            "indices": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "fps": {"type": "number"},
            "flippedname": {"type": "string"}
          },
          "required": ["name"],
          "additionalProperties": true
        }
      }},
      "deadAnimation": {
        "type": "object",
        "patternProperties": {
          ".+": {
            "type": "object",
            "properties": {
              "name": { "type": "string"},
              "loop": { "type": "boolean"},
              "indices": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              },
              "fps": {"type": "number"},
              "flippedname": {"type": "string"}
            },
            "required": ["name", "loop"]
          }
      }},
      "offset": {
        "type": "object",
        "patternProperties": {
          ".+": {
            "type": "array",
            "items": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "$comment": "make sure only x and y are given",
            "additionalItems": false,
            "minLength": 2
          }
        }
      },
      "deadOffset": {
        "type": "object",
        "patternProperties": {
          ".+": {
            "type": "array",
            "items": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "$comment": "make sure only x and y are given",
            "additionalItems": false,
            "minLength": 2
          }
        }
      },
      "flipx": {"type":"boolean"},
      "camOffset": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "enemyOffset": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "followCam": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "midpoint": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "like": {"type": "string"},
      "playAnim": {"type": "string"},
      "isPixel": {"type": "boolean"},
      "usesSpritesheetPacker": {"type": "boolean"},
      "size": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      }
  },
  "required": ["animation", "offset", "like", "playAnim"],
  "$comment": "dead things must have an offset AND an animation",
  "dependencies": {
    "deadOffset": ["deadAnimation"],
    "deadAnimation": ["deadOffset"]
  },
  "additionalProperties": false
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/parents.json
{
  "animation": {
    "idle": {
      "name": "Parent Christmas Idle",
      "loop": false
    },
    "singUP": {
      "name": "Parent Up Note Dad",
      "loop": false
    },
    "singDOWN": {
      "name": "Parent Down Note Dad",
      "loop": false
    },
    "singLEFT": {
      "name": "Parent Left Note Dad",
      "loop": false
    },
    "singRIGHT": {
      "name": "Parent Right Note Dad",
      "loop": false
    },
    "singLEFT-alt": {
      "name": "Parent Left Note Mom",
      "loop": false
    },
    "singRIGHT-alt": {
      "name": "Parent Right Note Mom",
      "loop": false
    },
    "singUP-alt": {
      "name": "Parent Up Note Mom",
      "loop": false
    },
    "singDOWN-alt": {
      "name": "Parent Down Note Mom",
      "loop": false
    }
  },
  "offset": {
    "idle": [0,0],
    "singUP": [-47,24],
    "singRIGHT": [-1,-23],
    "singLEFT": [-30, 16],
    "singDOWN": [-31, -29],
    "singUP-alt": [-47, 24],
    "singRIGHT-alt": [-1, -24],
    "singLEFT-alt": [-30,15],
    "singDOWN-alt": [-30, -27]
  },
  "flipx": false,
  "enemyOffset": [-500,0],
  "like": "parents",
  "playAnim": "idle"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/monster.json
{
  "animation": {
    "idle": {
      "name": "monster idle",
      "loop": true
    },
    "singUP": {
      "name": "monster up note",
      "loop": true
    },
    "singDOWN": {
      "name": "monster down",
      "loop": true
    },
    "singLEFT": {
      "name": "Monster left note",
      "loop": true
    },
    "singRIGHT": {
      "name": "Monster Right note",
      "loop": true
    }
  },
  "offset": {
    "idle": [0,0],
    "singUP": [-20,50],
    "singRIGHT": [-51,0],
    "singLEFT": [-30, 0],
    "singDOWN": [-30, -40]
  },
  "flipx": false,
  "enemyOffset": [0,100],
  "like": "monster",
  "playAnim": "idle"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/pico.json
{
  "animation": {
    "idle": {
      "name": "Pico Idle Dance",
      "loop": true
    },
    "singUP": {
      "name": "pico Up note0",
      "loop": false
    },
    "singDOWN": {
      "name": "Pico Down Note0",
      "loop": false
    },
    "singLEFT": {
      "name": "Pico NOTE LEFT0",
      "loop": false,
      "flippedname": "Pico Note Right0"
    },
    "singRIGHT": {
      "name": "BF NOTE RIGHT0",
      "loop": false,
      "flippedname": "Pico NOTE LEFT0"
    },
    "singLEFTmiss": {
      "name": "Pico NOTE LEFT miss",
      "loop": false,
      "flippedname": "Pico Note Right Miss"
    },
    "singRIGHTmiss": {
      "name": "Pico Note Right Miss",
      "loop": false,
      "flippedname": "Pico NOTE LEFT miss"
    },
    "singUPmiss": {
      "name": "pico Up note miss",
      "loop": false
    },
    "singDOWNmiss": {
      "name": "Pico Down Note MISS",
      "loop": false
    }
  },
  "offset": {
    "idle": [0,0],
    "singUP": [-29,27],
    "singRIGHT": [-68,-7],
    "singLEFT": [65, 9],
    "singDOWN": [200, -70],
    "singUPmiss": [-19, 67],
    "singRIGHTmiss": [-60, 41],
    "singLEFTmiss": [62,64],
    "singDOWNmiss": [210, -28]
  },
  "flipx": true,
  "camOffset": [600,0],
  "enemyOffset": [0,300],
  "like": "pico",
  "playAnim": "idle"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/bf-pixel.json
{
  "animation": {
    "idle": {
      "name": "BF IDLE",
      "loop": false
    },
    "singUP": {
      "name": "BF UP NOTE",
      "loop": false
    },
    "singDOWN": {
      "name": "BF DOWN NOTE",
      "loop": false
    },
    "singLEFT": {
      "name": "BF LEFT NOTE",
      "loop": false
    },
    "singRIGHT": {
      "name": "BF RIGHT NOTE",
      "loop": false
    },
    "singLEFTmiss": {
      "name": "BF LEFT MISS",
      "loop": false
    },
    "singRIGHTmiss": {
      "name": "BF RIGHT MISS",
      "loop": false
    },
    "singUPmiss": {
      "name": "BF UP MISS",
      "loop": false
    },
    "singDOWNmiss": {
      "name": "BF DOWN MISS",
      "loop": false
    }
  },
  "deadAnimation": {
    "firstDeath": {
      "name": "BF Dies pixel",
      "loop": false
    },
    "deathLoop": {
      "name": "Retry Loop",
      "loop": true
    },
    "deathConfirm": {
      "name": "RETRY CONFIRM",
      "loop": false
    },
    "singUP": {
      "name": "BF Dies pixel",
      "loop": false
    }
  },
  "offset": {
    "idle": [0,0],
    "singUP": [0,0],
    "singRIGHT": [0,0],
    "singLEFT": [0, 0],
    "singDOWN": [0, 0],
    "singUPmiss": [0,0],
    "singRIGHTmiss": [0, 0],
    "singLEFTmiss": [0,0],
    "singDOWNmiss": [0, 0]
  },
  "deadOffset": {
    "firstDeath": [0,0],
    "deathLoop": [-37,0],
    "deathConfirm": [-37,0]
  },
  "flipx": true,
  "enemyOffset": [0,350],
  "size": [-100,-100],
  "followCam": [-100,-100],
  "like": "bf-pixel",
  "isPixel": true,
  "playAnim": "idle"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/bf-car.json
{
  "animation": {
    "idle": {
      "name": "BF idle dance",
      "loop": false
    },
    "singUP": {
      "name": "BF NOTE UP0",
      "loop": false
    },
    "singDOWN": {
      "name": "BF NOTE DOWN0",
      "loop": false
    },
    "singLEFT": {
      "name": "BF NOTE LEFT0",
      "loop": false
    },
    "singRIGHT": {
      "name": "BF NOTE RIGHT0",
      "loop": false
    },
    "singLEFTmiss": {
      "name": "BF NOTE LEFT MISS",
      "loop": false
    },
    "singRIGHTmiss": {
      "name": "BF NOTE RIGHT MISS",
      "loop": false
    },
    "singUPmiss": {
      "name": "BF NOTE UP MISS",
      "loop": false
    },
    "singDOWNmiss": {
      "name": "BF NOTE DOWN MISS",
      "loop": false
    }
  },
  "offset": {
    "idle": [-5,0],
    "singUP": [-29,27],
    "singRIGHT": [-38,-7],
    "singLEFT": [12, -6],
    "singDOWN": [-11, -19],
    "singUPmiss": [-29, 27],
    "singRIGHTmiss": [-30, 21],
    "singLEFTmiss": [12,24],
    "singDOWNmiss": [-11, -19]
  },
  "flipx": true,
  "enemyOffset": [0,350],
  "followCam": [-100,-100],
  "like": "bf-car",
  "playAnim": "idle"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/dad.json
{
  "animation": {
    "idle": {
      "name": "Dad idle dance",
      "loop": true
    },
    "singUP": {
      "name": "Dad Sing Note UP",
      "loop": true
    },
    "singDOWN": {
      "name": "Dad Sing Note DOWN",
      "loop": true
    },
    "singLEFT": {
      "name": "Dad Sing Note LEFT",
      "loop": true
    },
    "singRIGHT": {
      "name": "Dad Sing Note RIGHT",
      "loop": true
    }
  },
  "offset": {
    "idle": [0,0],
    "singUP": [-6,50],
    "singRIGHT": [0,27],
    "singLEFT": [-10, 10],
    "singDOWN": [0, -30]
  },
  "flipx": false,
  "camOffset": [400,0],
  "like": "dad",
  "playAnim": "idle"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/spooky.json
{
  "animation": {
    "danceLeft": {
      "name": "spooky dance idle",
      "loop": false,
      "indices":[0,2,6],
      "fps": 12
    },
    "danceRight": {
      "name": "spooky dance idle",
      "loop": false,
      "indices":[8,10,12,14],
      "fps": 12
    },
    "singUP": {
      "name": "spooky UP NOTE",
      "loop": false
    },
    "singDOWN": {
      "name": "spooky DOWN note",
      "loop": false
    },
    "singLEFT": {
      "name": "note sing left",
      "loop": false
    },
    "singRIGHT": {
      "name": "spooky sing right",
      "loop": false
    }
  },
  "offset": {
    "danceLeft": [0,0],
    "danceRight": [0,0],
    "singUP": [-20,26],
    "singRIGHT": [-130,-7],
    "singLEFT": [130, -10],
    "singDOWN": [-50, -130]
  },
  "flipx": false,
  "enemyOffset": [0,200],
  "like": "spooky",
  "playAnim": "danceRight"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/gf.json
{
  "animation": {
    "danceLeft": {
      "name": "GF Dancing Beat",
      "loop": false,
      "indices": [30,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
    },
    "danceRight": {
      "name": "GF Dancing Beat",
      "loop": false,
      "indices": [15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
    },
    "cheer": {
      "name": "GF Cheer",
      "loop": false
    },
    "hairBlow": {
      "name": "GF Dancing Beat Hair blowing",
      "loop": false,
      "indices": [0,1,2,3]
    },
    "hairFall": {
      "name": "GF Dancing Beat Hair Landing",
      "loop": false,
      "indices": [0,1,2,3,4,5,6,7,8,9,10,11]
    },
    "singUP": {
      "name": "GF Up Note",
      "loop": false
    },
    "singDOWN": {
      "name": "GF Down Note",
      "loop": false
    },
    "singLEFT": {
      "name": "GF left note",
      "loop": false
    },
    "singRIGHT": {
      "name": "GF Right Note",
      "loop": false
    },
    "scared": {
      "name": "GF FEAR",
      "loop": false
    },
    "sad": {
      "name": "gf sad",
      "loop": false
    }
  },
  "offset": {
    "singUP": [0,4],
    "singRIGHT": [0,-20],
    "singLEFT": [0, -19],
    "singDOWN": [0, -20],
    "scared": [-2, -17],
    "cheer": [0,0],
    "sad": [-2,-2],
    "danceLeft": [0, -9],
    "danceRight": [0, -9],
    "hairBlow": [45, -8],
    "hairFall": [0, -9]
  },
  "flipx": false,
  "like": "gf",
  "playAnim": "danceRight"
}
