=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/custom_char_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "custom_char_schema.json",
  "type": "object",
  "properties": {
    "animation": {
      "type": "object",
      "patternProperties": {
        ".+": {
          "type": "object",
          "properties": {
            "name": { "type": "string"},
            "loop": { "type": "boolean"},
            "indices": {
              "type": "array",
              "items": {
                "type": "number"
              }
            },
            "fps": {"type": "number"},
            "flippedname": {"type": "string"}
          },
          "required": ["name"],
          "additionalProperties": true
        }
      }},
      "deadAnimation": {
        "type": "object",
        "patternProperties": {
          ".+": {
            "type": "object",
            "properties": {
              "name": { "type": "string"},
              "loop": { "type": "boolean"},
              "indices": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              },
              "fps": {"type": "number"},
              "flippedname": {"type": "string"}
            },
            "required": ["name", "loop"]
          }
      }},
      "offset": {
        "type": "object",
        "patternProperties": {
          ".+": {
            "type": "array",
            "items": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "$comment": "make sure only x and y are given",
            "additionalItems": false,
            "minLength": 2
          }
        }
      },
      "deadOffset": {
        "type": "object",
        "patternProperties": {
          ".+": {
            "type": "array",
            "items": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "$comment": "make sure only x and y are given",
            "additionalItems": false,
            "minLength": 2
          }
        }
      },
      "flipx": {"type":"boolean"},
      "camOffset": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "enemyOffset": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "followCam": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "midpoint": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      },
      "like": {"type": "string"},
      "playAnim": {"type": "string"},
      "isPixel": {"type": "boolean"},
      "usesSpritesheetPacker": {"type": "boolean"},
      "size": {
        "type": "array",
        "items": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "$comment": "make sure only x and y are given",
        "additionalItems": false,
        "minLength": 2
      }
  },
  "required": ["animation", "offset", "like", "playAnim"],
  "$comment": "dead things must have an offset AND an animation",
  "dependencies": {
    "deadOffset": ["deadAnimation"],
    "deadAnimation": ["deadOffset"]
  },
  "additionalProperties": false
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/gf-car.json
{
  "animation": {
    "danceLeft": {
      "name": "GF Dancing Beat Hair blowing CAR",
      "loop": false,
      "indices": [30,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
    },
    "danceRight": {
      "name": "GF Dancing Beat Hair blowing CAR",
      "loop": false,
      "indices": [15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
    },
    "singUP": {
      "name": "GF Dancing Beat Hair blowing CAR",
      "loop": false,
      "indices": [0]
    }
  },
  "offset": {
    "danceLeft": [0, 0],
    "danceRight": [0, 0]
  },
  "flipx": false,
  "like": "gf-car",
  "playAnim": "danceRight"
}

=== discus-sions/Fusion-Engine-Better/assets/preload/images/custom_chars/mom.json
{
  "animation": {
    "idle": {
      "name": "Mom Idle",
      "loop": false
    },
    "singUP": {
      "name": "Mom Up Pose",
      "loop": false
    },
    "singDOWN": {
      "name": "MOM DOWN POSE",
      "loop": false
    },
    "singLEFT": {
      "name": "Mom Left Pose",
      "loop": false
    },
    "singRIGHT": {
      "name": "Mom Pose Left",
      "loop": false
    }
  },
  "offset": {
    "idle": [0,0],
    "singUP": [14,71],
    "singRIGHT": [10,-60],
    "singLEFT": [250, -23],
    "singDOWN": [20, -160]
  },
  "flipx": false,
  "like": "mom",
  "followCam": [150,0],
  "playAnim": "idle"
}
